//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventeNative_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventeNativeEntities : DbContext
    {
        public EventeNativeEntities()
            : base("name=EventeNativeEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drzava> Drzava { get; set; }
        public virtual DbSet<Eventi> Eventi { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Interesovanja> Interesovanja { get; set; }
        public virtual DbSet<Kategorije> Kategorije { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_GetWithDrzavaGradKat(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_GetWithDrzavaGradKat", queryParameter);
        }
    
        public virtual int esp_Interesovanja_Update(Nullable<int> eventId, Nullable<int> korisnikId, Nullable<bool> zainteresovan, Nullable<bool> idem)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            var zainteresovanParameter = zainteresovan.HasValue ?
                new ObjectParameter("Zainteresovan", zainteresovan) :
                new ObjectParameter("Zainteresovan", typeof(bool));
    
            var idemParameter = idem.HasValue ?
                new ObjectParameter("Idem", idem) :
                new ObjectParameter("Idem", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Interesovanja_Update", eventIdParameter, korisnikIdParameter, zainteresovanParameter, idemParameter);
        }
    
        public virtual int esp_Korisnici_Insert(string ime, string prezime, string email, string korisnickoIme, string lozinka, Nullable<int> authToken)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            var authTokenParameter = authToken.HasValue ?
                new ObjectParameter("AuthToken", authToken) :
                new ObjectParameter("AuthToken", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("esp_Korisnici_Insert", imeParameter, prezimeParameter, emailParameter, korisnickoImeParameter, lozinkaParameter, authTokenParameter);
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Idem(Nullable<int> korisnik)
        {
            var korisnikParameter = korisnik.HasValue ?
                new ObjectParameter("Korisnik", korisnik) :
                new ObjectParameter("Korisnik", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Idem", korisnikParameter);
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Zainteresovani(Nullable<int> korisnik)
        {
            var korisnikParameter = korisnik.HasValue ?
                new ObjectParameter("Korisnik", korisnik) :
                new ObjectParameter("Korisnik", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Zainteresovani", korisnikParameter);
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Kulturni()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Kulturni");
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Muzicki()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Muzicki");
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Novi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Novi");
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Popularni()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Popularni");
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Preporuceni()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Preporuceni");
        }
    
        public virtual ObjectResult<esp_Eventi_GetWithDrzavaGradKat_Result> esp_Eventi_Sportski()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<esp_Eventi_GetWithDrzavaGradKat_Result>("esp_Eventi_Sportski");
        }
    
        public virtual ObjectResult<Nullable<bool>> esp_AuthToken(Nullable<int> authToken)
        {
            var authTokenParameter = authToken.HasValue ?
                new ObjectParameter("AuthToken", authToken) :
                new ObjectParameter("AuthToken", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("esp_AuthToken", authTokenParameter);
        }
    }
}
